export interface User { id: number; username: string; name: string; email: string; admin: boolean; state: string; avatar_url: string | null; bio: string | null; location: string | null; website_url: string | null; organization: string | null; status_emoji: string | null; status_message: string | null; created_at: string; updated_at?: string; }
export interface Namespace { id: number; name: string; path: string; type: string; visibility_level: number; description: string | null; parent_id?: number | null; owner_id?: number | null; avatar_url?: string | null; created_at?: string; updated_at?: string; }
export interface Project { id: number; name: string; path: string; full_path: string; namespace_id: number; namespace_path: string; creator_id: number; description: string | null; visibility_level: number; star_count: number; forks_count: number; archived: boolean; default_branch: string; topics: string[]; created_at: string; updated_at: string; is_starred?: boolean; namespace?: Namespace; creator?: User; last_activity_at?: string; merge_requests_enabled?: boolean; issues_enabled?: boolean; wiki_enabled?: boolean; starred?: boolean; forked_from_project_id?: number; }
export interface Label { id: number; title: string; color: string; description: string | null; project_id?: number | null; group_id?: number | null; created_at?: string; updated_at?: string; }
export interface Milestone { id: number; title: string; description: string | null; start_date: string | null; due_date: string | null; state: string; project_id?: number | null; group_id?: number | null; created_at?: string; updated_at?: string; }
export interface Issue { id: number; iid: number; title: string; description: string | null; project_id: number; author_id: number; author_username: string; assignee_id: number | null; assignee_username: string | null; milestone_id: number | null; state: string; created_at: string; updated_at: string; due_date: string | null; labels: Label[]; note_count?: number; notes_count?: number; author?: User; assignee?: User | null; milestone?: Milestone | null; project?: Project; closed_at?: string | null; weight?: number | null; confidential?: boolean; }
export interface MergeRequest { id: number; iid: number; title: string; description: string | null; project_id: number; author_id: number; author_username: string; source_branch: string; target_branch: string; state: string; merge_status: string; created_at: string; assignee_id?: number | null; updated_at?: string; merged_at?: string | null; merged_by_id?: number | null; note_count?: number; notes_count?: number; author?: User; assignee?: User | null; project?: Project; }
export interface Note { id: number; body: string; author_id: number; author_username: string; created_at: string; system: boolean; noteable_type?: string; noteable_id?: number; updated_at?: string; author?: User; }
export interface Member { id: number; user_id: number; username: string; name: string; access_level: number; access_level_name: string; created_at?: string; updated_at?: string; expires_at?: string | null; source_id?: number; source_type?: string; user?: User; }
export interface Todo { id: number; project_id: number; project_name: string; target_type: string; target_id: number; action: string; state: string; body: string | null; created_at: string; project?: Project; author?: User; }
export interface Group { id: number; name: string; path: string; description: string | null; visibility_level: number; members_count?: number; projects_count?: number; type?: string; avatar_url?: string | null; created_at?: string; updated_at?: string; }
export interface Stats { total_projects: number; total_issues: number; total_merge_requests: number; user_projects: number; user_todos: number; }
export interface ProjectFile { id: number; project_id: number; file_path: string; content: string; branch: string; last_commit_message: string; committed_by_id: number; created_at: string; updated_at: string; }
export interface TreeEntry { name: string; path: string; type: 'tree' | 'blob'; branch: string; }
export interface AuthResponse { user: User; session_token: string; }
export interface PaginatedProjects { projects: Project[]; total: number; page: number; limit: number; }
export interface PaginatedIssues { issues: Issue[]; total: number; page: number; limit: number; }
export interface PaginatedMergeRequests { merge_requests: MergeRequest[]; total: number; page: number; limit: number; }
export interface PaginatedTodos { todos: Todo[]; total: number; page: number; limit: number; }
export interface SearchResults { projects?: Project[]; issues?: Issue[]; merge_requests?: MergeRequest[]; users?: User[]; }
